# Generated by Django 3.0.8 on 2020-08-11 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20200810_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='lisitng',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='auctions.AuctionListings'),
        ),
        migrations.AddField(
            model_name='comments',
            name='lisitng',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='auctions.AuctionListings'),
        ),
        migrations.AddField(
            model_name='user',
            name='watchlist',
            field=models.ManyToManyField(blank=True, related_name='favorites', to='auctions.AuctionListings'),
        ),
        migrations.DeleteModel(
            name='Watchlist',
        ),
    ]
