# Generated by Django 3.0.8 on 2020-08-16 04:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20200811_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlistings',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchased_itemw', to=settings.AUTH_USER_MODEL),
        ),
    ]
