# Generated by Django 3.0.8 on 2020-08-16 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auctionlistings_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlistings',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
